FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

ARG DATABASE_URL
ARG DIRECT_URL
ARG JWT_SECRET
ARG CLOUDINARY_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET


ENV DATABASE_URL=$DATABASE_URL
ENV DIRECT_URL=$DIRECT_URL
ENV JWT_SECRET=$JWT_SECRET
ENV CLOUDINARY_NAME=$CLOUDINARY_NAME
ENV CLOUDINARI_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]
