version: '3.8'
services:
  dev-db:
    image: postgis/postgis:13-3.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: imobify
    networks:
      - imobify
    volumes:
    - .docker/postgres:/data/postgres

  test-db:
    image: postgis/postgis:13-3.4-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: imobify
    networks:
      - imobify
networks:
  imobify:
