POST http://localhost:3000/api/real-estate
Authorization: Bearer < announcer jwt token >
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

test real estate
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

real estate created for test purposes
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address"

street number zipcode city state
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="area"

55.5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="seeling_value"

220000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="renting_value"

1500
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="longitude"

< longitude >
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="latitude"

< latitude >
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="isActive"

true
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images[]"; filename="placeholder.png"
Content-Type: image/png

< ../assets/placeholder.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--